files:
  - source: '**/*.*'
    translation: /%original_path%/%original_file_name%
    languages_mapping:
      two_letters_code:
        zh-CN: ch
  - source: '*.csv'
    translation: /TEST/%two_letters_code%/%original_file_name%
    first_line_contains_header: '1'
    scheme: 'identifier,source_phrase,context,translation'
