files:
  - source: /*.xml
    translation: /translations/%two_letters_code%/sample(translations).xml
    languages_mapping:
      two_letters_code:
        zh-CN: ch
  - source: '*.csv'
    translation: /TEST/%two_letters_code%/%original_file_name%
    first_line_contains_header: '1'
    scheme: 'identifier,source_phrase,context,translation'
